export const SHOWCASE_TEXTURE_IMAGE = "/images/white-fabric-texture.jpg";

export const showcaseItems = [
  {
    id: "wedding-cinematic",
    src: "/images/gallery-covers/WOED0075.JPG",
    alt: "Wedding ceremony — aerial view",
    title: "Sarah & James",
    tag: "Cinematic cover",
    coverFrame: "cinematic",
    coverColor: "#4c0519",
  },
  {
    id: "portrait-minimal",
    src: "/images/gallery-covers/IMG_5566.JPG",
    alt: "Studio portrait session",
    title: "Studio Portraits",
    tag: "Minimal cover",
    coverFrame: "minimal",
  },
  {
    id: "editorial-card",
    src: "/images/gallery-covers/website_3-min.jpg",
    alt: "Editorial fashion portrait",
    title: "Editorial Session",
    tag: "Editorial card",
    coverFrame: "editorial-card",
    coverColor: "#f4f1ea",
  },
  {
    id: "engagement-overlay",
    src: "/images/gallery-covers/GIDO9970.JPG",
    alt: "Amoa & Mensa — engagement",
    title: "Amoa & Mensa",
    tag: "Overlay cover",
    coverFrame: "overlay",
    coverColor: "#1e3a5f",
  },
  {
    id: "lifestyle-collage",
    src: "/images/gallery-covers/GIDO9970.JPG",
    alt: "Colourful studio portrait",
    title: "Colour & Light",
    tag: "Collage cover",
    coverFrame: "collage",
    coverColor: "#0f172a",
  },
  {
    id: "family-bento",
    src: "/images/gallery-covers/IMG_5261.JPG",
    alt: "Traditional family portrait",
    title: "The Mensah Family",
    tag: "Bento cover",
    coverFrame: "bento",
    coverColor: "#14532d",
  },
  {
    id: "newborn-film",
    src: "/images/gallery-covers/IMG_2185.JPG",
    alt: "Portrait with emerald gele",
    title: "Heritage Portraits",
    tag: "Film border",
    coverFrame: "film-border",
    coverColor: "#44403c",
  },
] as const;
